### ISSUE TITLE
Compile on Alpine 3.12 fails - Includes proposed fix

### ISSUE THREAD

**Issue by jTd7bPLFb** [sappcoin-com/SAPP_1_3#30]
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Discord](https://discord.pivx.org).

#### If so, please list the steps to reproduce below:
- install alpine 3.12, install needed apk packages
"apk add build-base gcc abuild binutils autoconf automake libtool pkgconf python3 py3-virtualenv db-c++ db-dev gmp gmp-dev libevent libevent-dev git cmake boost-dev openssl openssl-dev boost boost-dev"
- clone SAPP git repo
cd SAPP
1. ./autogen.sh
2. ./configure --with-incompatible-bdb --disable-tests --disable-bench --disable-asm
3. cd src
4. make -j2 sapd
5. make -j2 sap-cli

### Expected behavior
sapd and sap-cli should compile

### Actual behavior
Error due to src/httpserver.cpp

Proposed FIX:
add
#include <deque>
to src/httpserver.cpp

**Comment by bedri** [comment]
This issue is fixed in #32 so closing.
